### ISSUE TITLE
pyGPCCA takes ages on reducible example to compute (non-existent) stationary distribution

### ISSUE THREAD

**Issue by Marius1311** [msmdev/pyGPCCA#18]
I'm running pyGPCCA via CellRank on a 3k samkples example - this usually takes 1-2 seconds on my machine. Now, in this particular case, it's a reducible example with 4 recurrent classes, see also the spectrum in Fig. 1 below. Running `g_fwd.compute_macrostates(n_states=5)`, where `g_fwd` is my CellRank estimator, takes ages (43 seconds) to compute a non-existent stationary distribution, see Fig. 2 below. What's the bottleneck here, why is this taking so long and how can we circumvent this useless computation (it tells me in the end that the stat. dist. does not exist, which I already knew. 

## Fig 1
![image](https://user-images.githubusercontent.com/24494650/107537968-c43c1a00-6bc3-11eb-9af8-3a2d79e19050.png)

## Fig. 2
![image](https://user-images.githubusercontent.com/24494650/107538177-f77ea900-6bc3-11eb-9f00-0baa45a9a682.png)

**Comment by msmdev** [comment]
@Marius1311, any news on this?

**Comment by Marius1311** [comment]
Yes, this will be solved by #22

**Comment by Marius1311** [comment]
Solved with #22 .
