### ISSUE TITLE
Potentially threshold too tight

### ISSUE THREAD

**Issue by Marius1311** [msmdev/pyGPCCA#19]
For the reducible example of #18, pyGPCCA initially failed because
```
ValueError: The subspace of Q derived by shifting a non-constant first (Schur)vector to the right and setting the first (Schur) vector equal sqrt(eta) doesn't match the subspace of the original Q! The subspace angles are: [1.99397121e-08 8.43619247e-16 8.10190380e-16 7.21384005e-16
 6.71149074e-16 5.69574404e-16 4.94529500e-16 4.71417422e-16
 3.79393164e-16 3.18402416e-16 3.10074041e-16]. Number of clusters: 11.
```
However, the largest deviation from zero here was order of magnitude 1E-8. Either we should change the threshold or this explains the difficulties we see in #18. To move past this, I changed the threshold to 1E-7 locally (in L156 and L135). Then, I encountered the issue described in #18.

**Comment by msmdev** [comment]
@Marius1311 actually it is hard to guess what is happening here. I wouldn't expect the shifting of the constant 1 vector to cause any significant change in the subspace.
I assume that something is off here and thus the strange behavior in #18 occurs.
Thus, you might concentrate on finding the cause for this subspace deterioration first.

**Comment by Marius1311** [comment]
I have to admit I didn't check that particular case again with the adjusted thresholds, but I would suggest we close the issue for now.
