### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by michalk8** [msmdev/pyGPCCA#2]
Include general information, installation instructions very small code example.

**Comment by Marius1311** [comment]
For the record: we tried together but got stuck due to 
```bash
===============================================================================
             Configuring PETSc to compile on your system                       
===============================================================================
TESTING: checkCCompiler from config.setCompilers(config/BuildSystem/config/setCompilers.py:635)                                                                    *******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
C compiler you provided with -with-cc=mpicc cannot be found or does not work.
Cannot compile/link C with mpicc.
*******************************************************************************
```

**Comment by msmdev** [comment]
Ok, is mpi support obligatory for PETSc or can you option it out at compile time?

**Comment by michalk8** [comment]
No, but highly recommended: https://www.mcs.anl.gov/petsc/petsc4py-current/docs/usrman/install.html
Marius has MPICH locally, however on the CI, i use Open MPI - think in the `configure`, something needs to be specified.

**Comment by Marius1311** [comment]
What's currently still missing? Can we gather some to do's here?

**Comment by msmdev** [comment]
I assume the main to-do's are collected here
https://github.com/msmdev/pyGPCCA/issues/1#issue-785909228

**Comment by msmdev** [comment]
I will try to fill the README today.
How is the state regarding the PETSc/SLEPc MacOS installation?
If you solved it, could you add some documentation regarding the installation?

**Comment by michalk8** [comment]
>  If you solved it, could you add some documentation regarding the installation?

Not on Marius' PC, but we can use the steps as it's done in the CI.

**Comment by msmdev** [comment]
I added some more detailed description of G-PCCA/pyGPCCA and an usage example to the README in the update-readme branch.
@michalk8 @Marius1311 could you mb. add some more detailed installation instructions?
