### ISSUE TITLE
Patch release

### ISSUE THREAD

**Issue by Marius1311** [msmdev/pyGPCCA#31]
Our reproducibility repo we're setting up for CellRank requires the adjusted thresholds of #30. To ease reproducibility for users, we should make a patch release of pyGPCCA, even though it's a very small one.

**Comment by Marius1311** [comment]
Yes, I would still vote for the patch release. There a few other things we still have to do before that, I'll ping you when it's time!

**Comment by michalk8** [comment]
> Yes, I would still vote for the patch release. There a few other things we still have to do before that, I'll ping you when it's time!

@Marius1311 in light of #33 , would double-check whether there isn't something we want to add anymore.

**Comment by michalk8** [comment]
closed via #35
