### ISSUE TITLE
Linting fails

### ISSUE THREAD

**Issue by msmdev** [msmdev/pyGPCCA#32]
Currently linting fails for check-docs. Command failing is `sphinx-build -q -W --keep-going -b linkcheck /home/runner/work/pyGPCCA/pyGPCCA/docs/source /home/runner/work/pyGPCCA/pyGPCCA/docs/build/linkchec`
(see [here](https://github.com/msmdev/pyGPCCA/runs/4137481237?check_suite_focus=true).

Additionally, there is a (unrelated) warning: "macOS-latest workflows will use macOS-11 soon. For more details, see https://github.com/actions/virtual-environments/issues/4060"

**Comment by msmdev** [comment]
@michalk8, appears to be related with https://pepy.tech/project/pygpcca being unreachable. Thus the link to the pypi downloads badge can't be established.

**Comment by michalk8** [comment]
There was an issue on raised on ``pepy``, seems to have been fixed by now, am re-running the linting jobs to verify. If they pass, think we can close this.

**Comment by michalk8** [comment]
Closing this since the jobs now pass, feel free to re-open if you want e.g. less stringent with the linting (could add a whitelist for a few links).
