### ISSUE TITLE
Prevent use of PETSc/SLEPc with complex support.

### ISSUE THREAD

**Issue by msmdev** [msmdev/pyGPCCA#51]
In issue #48, pyGPCCA was used together with PETSc/SLEPc compiled with complex support [here](https://github.com/msmdev/pyGPCCA/issues/48#issue-1436391359). This is actually a misuse, since pyGPCCA should be only used with PETSc/SLEPc compiled with real support. Thus, we should prevent users from making this mistake by raising an exception if PETSc/SLEPc were compiled with complex support (with compile flag `--with-scalar-type=complex`).

**Comment by msmdev** [comment]
@michalk8, any idea how to handle this?

**Comment by michalk8** [comment]
> @michalk8, any idea how to handle this?

I think there might be some flag in PETSc/SLEPc package we could check at runtime during import.
Alternatively, we might be able to specify it in the `recipe.yml` on `conda-forge`.
