### ISSUE TITLE
Install pygpcca from conda-forge on silicon mac

### ISSUE THREAD

**Issue by Marius1311** [msmdev/pyGPCCA#52]
When running `conda install -c conda-forge pygpcca`, I get 
`PackagesNotFoundError: The following packages are not available from current channels:

  - pygpcca

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

I suppose that's because I'm on an M1 Mac with silicon (arm64) architecture. The package clearly exists on conda-forge: https://anaconda.org/conda-forge/pygpcca

**Comment by Marius1311** [comment]
I can install it from pypi with no problem, though.

**Comment by michalk8** [comment]
Related to https://github.com/conda-forge/pygpcca-feedstock/pull/12

**Comment by michalk8** [comment]
Should be fixed on https://github.com/conda-forge/pygpcca-feedstock/pull/13 is merged.

**Comment by msmdev** [comment]
@Marius1311, did merging https://github.com/conda-forge/pygpcca-feedstock/pull/13 fix this?

**Comment by msmdev** [comment]
@Marius1311, did https://github.com/conda-forge/pygpcca-feedstock/pull/15#issuecomment-1427712343 fix this?

**Comment by Marius1311** [comment]
Yes, I just tried installing from conda-forge on the same machine and it works now! I think this can be closed.

**Comment by Marius1311** [comment]
thanks for fixing this!

**Comment by msmdev** [comment]
Perfect, closing this :)
