### ISSUE TITLE
Readthedocs

### ISSUE THREAD

**Issue by michalk8** [msmdev/pyGPCCA#8]
Push the documentation to readthedocs.yml. TODOs:
- [x] create .readthedocs.yml
- [ ] update .css file (for now, just increase the width/change style)
- [x] move intallation troubleshooting from README
- [ ] update badges, check links
- [ ] add a small usage notebook - I think this should this replace the usage @msmdev (i.e. just move the explanations into the notebook)
- [ ] add binder links, related to above (I will need a requirements file which can run the notebook - will most likely need numpy/scipy/matplotlib only)

**Comment by msmdev** [comment]
OK, will create a small notebook with some example matrix from the tests.
@michalk8 were (folder) should the .ipynb be placed?
